#!/bin/bash

echo "🚀 Deploying TARU Backend to Railway.app"
echo "========================================"

# Check if Railway CLI is installed
if ! command -v railway &> /dev/null; then
    echo "❌ Railway CLI not found. Installing..."
    npm install -g @railway/cli
fi

# Generate secure JWT secret
JWT_SECRET=$(openssl rand -base64 32)
echo "🔐 Generated JWT Secret: $JWT_SECRET"

echo ""
echo "📋 Deployment Steps:"
echo "1. Run: railway login"
echo "2. Run: railway init"
echo "3. Run: railway add postgresql"
echo "4. Run: railway up"
echo ""
echo "🔧 Environment Variables to set in Railway dashboard:"
echo "   JWT_SECRET: $JWT_SECRET"
echo "   NODE_ENV: production"
echo "   DATABASE_URL: (auto-generated by Railway)"
echo ""
echo "✅ After deployment, test your endpoints:"
echo "   Health: https://your-app.up.railway.app/health"
echo "   IFS Check-in: https://your-app.up.railway.app/ifs/checkin"
echo ""
echo "🎯 Ready to deploy! Run the commands above."


